name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Check python
      run: which /usr/bin/python3
    - name: Check python3
      run: which /usr/bin/python3
    - name: Set Python environment variable
      run: npm config --global set python /usr/bin/python3
    - name: Install
      uses: borales/actions-yarn@v2.3.0
      env:
        PYTHON: ${{ matrix.python }}
      with:
        cmd: install
    - name: Build
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build
    - name: Test
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: test
